import 'package:flutter/material.dart';

final List<Color> colors = [
  const Color(0xFFCFCBF9),
  const Color(0xFFF9EECB),
  const Color(0xFFF9CBCF),
  const Color(0xFFEACBF9),
  const Color(0xFFCBF9DA),
  const Color(0xFFCFCBF9),
  const Color(0xFFF9EECB),
  const Color(0xFFF9CBCF),
  const Color(0xFFEACBF9),
  const Color(0xFFCBF9DA),
  const Color(0xFFCFCBF9),
  const Color(0xFFF9EECB),
  const Color(0xFFF9CBCF),
  const Color(0xFFEACBF9),
  const Color(0xFFCBF9DA),
  const Color(0xFFCFCBF9),
  const Color(0xFFF9EECB),
  const Color(0xFFF9CBCF),
  const Color(0xFFEACBF9),
  const Color(0xFFCBF9DA),
  const Color(0xFFCFCBF9),
  const Color(0xFFF9EECB),
  const Color(0xFFF9CBCF),
  const Color(0xFFEACBF9),
  const Color(0xFFCBF9DA),
  const Color(0xFFCFCBF9),
  const Color(0xFFF9EECB),
  const Color(0xFFF9CBCF),
  const Color(0xFFEACBF9),
  Color.fromARGB(255, 203, 249, 218),
];
