name: birth_daily
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  go_router: ^14.1.3
  firebase_ui_auth: ^1.15.0
  firebase_core: ^3.1.0
  firebase_ui_oauth_google: ^1.3.3
  google_sign_in: ^6.2.1
  firebase_messaging: ^15.0.1
  flutter_bloc: ^8.1.6
  cloud_firestore: ^5.0.1
  firebase_ui_firestore: ^1.6.4
  dio: ^5.4.3+1
  flutter_svg: ^2.0.10+1
  firebase_auth: ^5.1.1
  table_calendar: ^3.1.2
  firebase_ui_oauth_apple: ^1.2.21
  flutter_slidable: ^3.1.0
  font_awesome_flutter: ^10.7.0
  smooth_page_indicator: ^1.1.0
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.4.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/avatars/
    - assets/logo.png
    - assets/splash/splash.png

flutter_native_splash:
  android: true
  ios: true
  web: false

  color: "#FFFFFF"
  image: "assets/splash/splash.png"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/foreground_icon.png"
